openshift/cluster-csi-snapshot-controller-operator

Dockerfile, Dockerfile.rhel7, manifests/03_configmap.yaml, manifests/05_operator_rbac.yaml, manifests/08_deployment.yaml
Add manifests to work in-cluster
- Using "admin" role for the operator - the operator reads various secrets from kube-system. It's commonly used in all other operators.
- Adding operator deployment.
- Adding config-map for configuration override, as it seems to be common in OpenShift.
- Use Go 1.13 for images
=> Fix manifests

manifests/08_deployment.yaml, pkg/operator/operator.go
With this PR, ClusterOperator.Status.Versions are filled:
```
versions:
- name: operator
version: 4.4.0-0.okd-2020-01-20-000453
- name: csi-snapshot-controller
version: 4.4.0-0.okd-2020-01-20-000453
```
=> Add version to CSISnapshotController.Status and ClusterOperator

assets/csi_controller_deployment.yaml, pkg/generated/bindata.go
So it's not evicted from nodes. We need it running in a cluster, the same way as the operator.
=> Make the controller (operand) critical

manifests/08_clusteroperator.yaml
To be in sync with code in sync.go. This should fix cluster installation, when CVO was waiting for version of `csi-snapshot-controller-operator`, while the operator reported its version as `operator`.
=> Fix operator version name

pkg/operator/operator.go, pkg/operator/sync.go
Log all informer events on log level "Trace". This will show us what informer caused `sync()` to be called.
The log level must be set in CSISnapshotInformer instance instead of command line (learned the hard way...):
```
apiVersion: operator.openshift.io/v1
kind: CSISnapshotController
metadata:
name: cluster
spec:
operatorLogLevel: Trace
managementState: Managed
```
I haven't found any easier way how to get `Kind` from `interface{}`.
=> Log informer events

pkg/operator/sync.go
The operator needs to update Deployment it operates when a change is required by user (or something else).
Source of these changes are:
* `CSISnapshotController.Spec.LogLevel` - handled in this PR.
* Env. variable `OPERAND_IMAGE` - it can't change during the operator lifetime and I checked the operator correctly applies new `OPERAND_IMAGE` to Deployment on operator restart.
Note that this PR applies changes to the Deployment on all changes in `CSISnapshotController.Spec`, which is not optimal, but it should be sufficient enough. At least authentication operator does the same.
=> Force update Deployment when CSISnapshotController.LogLevel is changed

Dockerfile, Dockerfile.rhel7, assets/csi_controller_deployment.yaml, manifests/07_deployment.yaml, manifests/image-references, pkg/generated/bindata.go, pkg/operator/operator.go, pkg/operator/starter.go
And be part of release payload.
\+ Fix issues found by operator e2e  tests
* use IfNotPresent pull policy
* assign some resources to the controller (TODO: check with a real cluster)
* add resource references
=> Enable the operator to be managed by CVO

pkg/operator/operator.go
We always read Deployments from API server.
=> Remove unused deployment lister

pkg/operator/operator.go, pkg/operator/sync.go
Force controller deployment update when:
- the operator version changes, it could have a different controller Deployment template. So force-deploy it.
- the controller version changes, so the Deployment gets new image.
=> Update Deployment on image version change

pkg/operator/operator.go, pkg/operator/starter.go
Tested on a cluster, there are logs both from the csi-snapshot-controller and csi-snapshot-controller-operator included in must-gather now.
=> Fix must-gather namespace names

manifests/07_deployment.yaml, manifests/image-references
Use the latest OKD images when installing the operator manually via `oc create -f manifests/`.
=> Bug 1798448: Use Origin images from quay.io/openshift

assets/volumesnapshotclasses.yaml, assets/volumesnapshotcontents.yaml, assets/volumesnapshots.yaml, pkg/generated/bindata.go
**What type of PR is this?**
/kind bug
**What this PR does / why we need it**:
Includes additional information for the `get` command for the VolumeSnapshot* CRDs. This is, effectively, a backport of https://github.com/kubernetes-csi/external-snapshotter/pull/260 ; however, since we simply copy the CRDs I've copied the changes here.
**Does this PR introduce a user-facing change?**:
```release-note
Prints additional details when using kubectl get on VolumeSnapshot, VolumeSnapshotContent, and VolumeSnapshotClass API objects.
```
=> Bug 1800437, Bug 1800470, Bug 1800477: Update getters to match upstream

vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
This is cherry-pick of https://github.com/openshift/library-go/pull/787.
=> Bug 1829320: UPSTREAM: 787: Fix ClusterOperator event when version changes

pkg/operator/operator.go, pkg/operator/operator_test.go, pkg/operator/sync.go
The operator should print a human friendly message when v1alpha1 CRDs are detected. Such cluster can't support OCP v1beta1 version of snapshots and users should know why.
Example of such error:
```
status:
conditions:
- lastTransitionTime: "2020-06-08T13:14:49Z"
status: "False"
type: ManagementStateDegraded
- lastTransitionTime: "2020-06-08T13:14:50Z"
message: 'failed to sync CRDs: cluster-csi-snapshot-controller-operator does
not support v1alpha1 version of snapshot CRDs volumesnapshots.snapshot.storage.k8s.io,
volumesnapshotcontents.snapshot.storage.k8s.io, volumesnapshotclasses.snapshot.storage.k8s.io
installed by user or 3rd party controller'
reason: AlphaCRDsExist
status: "True"
type: Degraded
readyReplicas: 0
```
cc @openshift/storage
=> Bug 1807615: Add extra check for v1alpha CRD

manifests/05_user_rbac.yaml
- storage-admin owns the cluster-scoped objects and can read namespaced
CRs.
- Namespace admin / editor owns namespaced objects.
- Namespace viewer can read namespaced objects.
- Basic uses can read VolumeSnapshotClasses.
/hold
It needs https://github.com/openshift/openshift-apiserver/pull/113 merged first.
=> Bug 1841035: Add permissions to snapshot CRs to various cluster roles

manifests/07_deployment.yaml
Rename the operator container to allow for more reasonable debugging.
=> Bug 1876858: manifests: rename operator container to be more descriptive

pkg/operator/sync.go
This PR updates the status reasons in failure/progressing scenarios to be a bit more explicit. It keeps "AsExpected" for success conditions.
=> Bug 1879475: Updated status reasons to be more explicit in failure scenarios

manifests/00_namespace.yaml
The namespace manifest is in cluster-storage-operator manifests and it's created before CVO evaluates csnapshot operator manifests (i.e. it has lower runlevel).
cc @openshift/storage 
/hold
for https://github.com/openshift/cluster-storage-operator/pull/89 to be merged first
=> Bug 1879365: Remove namespace creation

pkg/operator/sync.go
Versions should be set after the operand has rolled out.
=> Bug 1839239: Update version only after having rolled out the new operand

manifests/02_operator_cr.yaml, manifests/03_configmap.yaml, manifests/03_service.yaml, manifests/04_serviceaccount.yaml, manifests/05_operand_rbac.yaml, manifests/05_operator_rbac.yaml, manifests/05_user_rbac.yaml, manifests/07_deployment.yaml, manifests/08_clusteroperator.yaml
This is matches openshift/enhancements#414 and doesn't change existing behavior
=> add current profile annotations to CVO manifests

assets/webhook_deployment.yaml, manifests/07_deployment.yaml, pkg/generated/bindata.go
And adjust CSI snapshot operator memory request. Measured in https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.7.0-0.nightly/release/4.7.0-0.nightly-2020-12-04-013308:
* The operator took 63MiB for most of the CI run: `container_memory_max_usage_bytes{container="csi-snapshot-controller-operator",..., pod="csi-snapshot-controller-operator-8555964b44-lzsxd"} 66138112`
* The webhook took 17 MiB for most of the CI run: `container_memory_max_usage_bytes{container="webhook", ..., pod="csi-snapshot-webhook-f7bb59b75-8wqcq"} 18132992`
For the record, snapshot-controller memory requirement is OK.
=> Bug 1905320: Add memory limit for webhook container.

assets/volumesnapshotclasses.yaml, assets/volumesnapshotcontents.yaml, assets/volumesnapshots.yaml, pkg/generated/bindata.go
This moves the snapshot CRDs to v1, as it's expected for the k8s 1.20 tests.
=> Bug 1906518: Update Snapshot CRDs to v1

manifests/09_webhook_config.yaml
Upstream webhook, as it is now, can validate only v1beta1 objects and fails any v1 object validation.
cc @openshift/storage 
All Feature:VolumeSnapshotDataSource tests are failing, see the BZ for details.
=> Bug 1908349: Don't validate v1 objects

assets/webhook_config.yaml, pkg/generated/bindata.go
v1 API validation was disabled for CI, let's enable it now
=> Bug 1907287: Use webhook for v1 snapshot API

assets/webhook_config.yaml, manifests/02_operator_cr.yaml, manifests/03_configmap.yaml, manifests/03_service.yaml, manifests/04_serviceaccount.yaml, manifests/05_operand_rbac.yaml, manifests/05_operator_rbac.yaml, manifests/05_user_rbac.yaml, manifests/07_deployment.yaml, manifests/08_webhook_service.yaml, manifests/10_clusteroperator.yaml, pkg/generated/bindata.go
This implements phase 1 of openshift/enhancements#482
=> Bug 1915473: Annotate manifests for single-node-developer cluster profile

manifests/07_deployment.yaml, manifests/08_webhook_service.yaml, manifests/10_clusteroperator.yaml
The operator should be installed on ROKS. Fix annotations in files that missed it.
=> Bug 1926444: Fix installation on ROKS

assets/csi_controller_deployment.yaml, assets/webhook_deployment.yaml, manifests/07_deployment.yaml, pkg/generated/bindata.go
In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> Add management workload annotations

manifests/07_deployment.yaml, manifests/10_clusteroperator.yaml
Follow up to https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/79
The annotations to exclude manifests should also be removed.
=> Bug 1951066: Remove exclude annotation from manifests to include in ROKS

manifests/05_operator_rbac.yaml
`ClusterRoleBinding` is [cluster][1]-[scoped][2], and the presence of this property in the manifest [causes the CVO to hot-loop][3].
[1]: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrolebinding-example
[2]: https://github.com/kubernetes/api/blob/9b64426eca51a74faa7cc9bd732a533d339c69c2/rbac/v1/types.go#L195-L200
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=1961538
=> Bug 1961538: manifests/05_operator_rbac: Drop the unused namespace property

assets/volumesnapshotcontents.yaml, pkg/generated/bindata.go
Getting the VolumeSnapshotContents from CLI will print also the VolumeSnapshot it references. This is however not sufficient to identify the correct VolumeSnapshot object since it's namespaced. This patch adds alos the namespace column to the printed information.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1965263
=> Bug 1965263: VolumeSnapshotContents listing should print also namespace of the VolumeSnapshot ref.

.gitignore, Makefile, manifests/07_deployment-ibm-cloud-managed.yaml, manifests/07_deployment.yaml, profile-patches/ibm-cloud-managed/07_deployment.yaml-patch
Adds patch to generate an ibm-cloud-managed specific deployment manifest for this operator.
This is needed to deploy the operator in a topology where there are no master nodes.
=> Add ibm-cloud-managed profile patch for operator deployment

assets/volumesnapshotclasses.yaml, assets/volumesnapshotcontents.yaml, assets/volumesnapshots.yaml
To version released in upstream external-attacher v5.0.1 released with Kubernetes 1.23.
Namely, v1beta1 API is officially deprecated and v1 is used to store the snapshots.
=> Bug 2043130: Bump snapshot CRDs

pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/bindata/bindata.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/modules.txt
Builds on top of https://github.com/openshift/library-go/pull/1246 and WithIsSNOCheck from https://github.com/openshift/library-go/pull/1238.
=> bug 2039670: Skip deployment of PDBs on the SNO topology

manifests/07_deployment-ibm-cloud-managed.yaml, manifests/07_deployment.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
  "objectRef": "openshift-cluster-storage-operator/deployments/csi-snapshot-controller-operator",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"csi-snapshot-controller-operator\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"csi-snapshot-controller-operator\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container …
```
=> manifests/deployment: comply to restricted pod security level

assets/csi_controller_deployment.yaml, assets/webhook_deployment.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
$ oc -n openshift-cluster-storage-operator logs csi-snapshot-controller-operator-66578b8669-kdbnl | grep "would violate PodSecurity"
W0512 01:45:31.019201 1 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "webhook" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), …
```
=> AUTH-133: assets: comply to restricted pod security level

manifests/05_operator_apiserver_authentication_reader.yaml, manifests/05_operator_role.yaml
The operator fails with:
> Unable to get configmap/extension-apiserver-authentication in kube-system. Usually fixed by
> 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
And:
> builder.go:230] unable to get owner reference (falling back to namespace): replicasets.apps "csi-snapshot-controller-operator-597c947cf" is forbidden: User "system:serviceaccount:openshift-cluster-storage-operator:csi-snapshot-controller-operator" cannot get resource "replicasets" in API group "apps" in the namespace "openshift-cluster-storage-operator"
This was caused by a recent RBAC refactoring. Add the missing RoleBinding + update Role.
=> OCPBUGS-990: Add RBAC to read extension-apiserver-authentication in kube-system

pkg/operator/starter.go
On SingleNodeClusters, don't remove PodDisruptionBudget, because the operator does not have permissions for it. And the PDB should not exist there anyway.
cc @openshift/storage
=> OCPBUGS-3973: Don't remove PDB on SNO clusters

pkg/operator/starter.go
`admin-kubeconfig` is only for external end users and does not work when the cluster is `endpointAccess: Private`.  Use the `service-network-admin-kubeconfig` instead.
https://issues.redhat.com/browse/OCPBUGS-4490
=> OCPBUGS-4490: hypershift: use correct kubeconfig secret for csi-snapshot-controller

manifests/05_operator_role-hypershift.yaml, pkg/operator/starter.go, profile-patches/hypershift/05_operator_role.yaml-patch
Based on https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/145
Set operand properties like nodeSelector, node / pod affinity and toleration for HyperShift.
=> OCPBUGS-8691: Hypershift: set Deployment properties

manifests/05_operator_remove_cluster_admin.yaml
The snapshot operator has proper RBACs in 4.12 and should not use cluster-admin role. Therefore delete its ClusterRoleBinding during upgrade.
=> OCPBUGS-8374: [4.12] remove cluster-admin role.

manifests/07_deployment-hypershift.yaml, manifests/07_deployment-ibm-cloud-managed.yaml, manifests/07_deployment.yaml
Explicitly ask for readOnlyFilesystem set to false. Fixes https://issues.redhat.com/browse/OCPBUGS-3680
=> OCPBUGS-3680: Set readOnlyRootFilesystem to false

assets/webhook_service.yaml
We are preventing/deleting any webhook that runs in a hosted cluster and targets a service running in the management cluster here: https://github.com/openshift/hypershift/pull/2775
This PR adds a label to the `csi-snapshot-webhook` service to ensure `snapshot.storage.k8s.io` webhook doesn't get deleted.
Although the original PR was merged, there was a bug which made it not detect the `snapshot.storage.k8s.io` webhook, otherwise it would have been deleted. This needs to be merged before the fix is merged in the hypershit repo https://github.com/openshift/hypershift/pull/2898
Fixes #[HOSTEDCP-1063](https://issues.redhat.com/browse/HOSTEDCP-1063)
=> HOSTEDCP-1063: allow webhooks in hosted clusters to reach csi-snapshot-webhook service

manifests/07_deployment-hypershift.yaml, manifests/07_deployment-ibm-cloud-managed.yaml, manifests/07_deployment.yaml
Fixes https://issues.redhat.com/browse/OCPBUGS-3680
=> OCPBUGS-3680: Move readonlyRootFilesystem to the right place

manifests/05_operator_role-hypershift.yaml, manifests/05_operator_role.yaml, pkg/operator/starter.go
Adding `WithSecretHashAnnotationHook()` for `csi-snapshot-webhook-secret` ensures that new annotation is published in `csi-snapshot-webhook` Deployment. This, in turn, leads to webhook pods restart.
=> STOR-1443: Restart webhook Pods if `csi-snapshot-webhook-secret` changed

manifests/07_deployment-hypershift.yaml, manifests/07_deployment-ibm-cloud-managed.yaml, manifests/07_deployment.yaml
fixes https://issues.redhat.com/browse/OCPBUGS-18801
=> OCPBUGS-18801: Move readonlyRootFilesystem to the right place - 4.14

assets/csi_controller_deployment.yaml, assets/webhook_deployment.yaml
adding "automountServiceAccountToken" false to webhook and csi-snapshot-controller deployments as the deployments dont need the service account mount
[HOSTEDCP-1308](https://issues.redhat.com/browse/HOSTEDCP-1308)
=> HOSTEDCP-1308: add KAS access label to csi-snapshot-controller and csi-snapshot-webhook

assets/csi_controller_deployment.yaml, assets/webhook_deployment.yaml
Revert https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/182
webhook and controller pods don't need management KAS access.
=> HOSTEDCP-1308: Revert "HOSTEDCP-1308: add KAS access label to csi-snapshot-controller and csi-snapshot-webhook"

assets/assets.go, assets/rbac/csi_snapshot_controller_clusterrole.yaml, assets/rbac/csi_snapshot_controller_clusterrolebinding.yaml, assets/rbac/webhook_clusterrole.yaml, assets/rbac/webhook_clusterrolebinding.yaml, assets/volumegroupnapshotclasses.yaml, assets/volumegroupnapshotcontents.yaml, assets/volumegroupnapshots.yaml, assets/webhook_deployment.yaml, assets/webhook_serviceaccount.yaml, manifests/05_operator_clusterrole.yaml, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go, vendor/modules.txt
=> STOR-1700: Pass VolumeGroupSnapshot argument if feature is enabled

go.mod, pkg/operator/starter.go
Set's the RunAsNonRoot to false and the RunAsUser to 1001 if the management cluster HyperShift is running on does not support SCC. This is needed for running HyperShift on non-OpenShift management cluster's such as AKS as part of [OCPSTRAT-460](https://issues.redhat.com/browse/OCPSTRAT-460).
=> STOR-1805: Set SecurityContext for HyperShift

assets/assets.go, assets/rbac/webhook_clusterrole.yaml, assets/rbac/webhook_clusterrolebinding.yaml, assets/webhook_deployment.yaml, assets/webhook_serviceaccount.yaml, manifests/05_operator_clusterrole.yaml, pkg/operator/starter.go
Manual backport of https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/202 to 4.15 -- but only the parts required to get the correct permissions for the webhook. We don't want any of the volumegroupsnapshot changes backported.
/cc @openshift/storage @bertinatto @Phaow
=> [4.15] OCPBUGS-31599: create suitable role and roleBinding for csi-snapshot-webhook

assets/volumesnapshotclasses.yaml, assets/volumesnapshotcontents.yaml, assets/volumesnapshots.yaml
Update CRDs in `/assets` according to CRDs in https://github.com/kubernetes-csi/external-snapshotter/tree/v7.0.0/client/config/crd
=> STOR-1573: Update manifests to v7.0.0

assets/csi_controller_deployment.yaml, assets/webhook_deployment.yaml
All openshift operators must include FallbackToLogsOnError to ease debugging.
=> OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

assets/volumegroupsnapshotclasses.yaml, assets/volumegroupsnapshotcontents.yaml, assets/volumegroupsnapshots.yaml, assets/volumesnapshotclasses.yaml, assets/volumesnapshotcontents.yaml, assets/volumesnapshots.yaml, assets/webhook_config.yaml
Update api extensions to upstream which implemented way of validating sources instead of using webhook. 
This is change is needed by https://github.com/openshift/csi-external-snapshotter/pull/156.
=> STOR-1593: Update api extensions to upstream

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/deploymentcontroller/deployment_controller.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiregistration.go, vendor/modules.txt
To pull deployment controller fix:
https://github.com/openshift/library-go/pull/1940
=> OCPBUGS-24588: bump library-go

README.md, manifests/07_deployment.yaml, profile-patches/hypershift/07_deployment.yaml-patch, profile-patches/ibm-cloud-managed/07_deployment.yaml-patch
Enable readOnlyFileSystem in the operator for security concerns. 
Recommended for all containers running in kubernetes.
=> STOR-2126: Enable readOnlyFileSystem

assets/snapshotmetadataservices.yaml, pkg/operator/starter.go
https://issues.redhat.com/browse/STOR-2465
Depends on https://github.com/openshift/api/pull/2381
/cc @openshift/storage
=> STOR-2465: Add ExternalSnapshotMetadata CRD

assets/csi_controller_deployment.yaml, manifests/07_deployment-hypershift.yaml, manifests/07_deployment-ibm-cloud-managed.yaml, profile-patches/hypershift/07_deployment.yaml-patch, profile-patches/ibm-cloud-managed/07_deployment.yaml-patch
https://issues.redhat.com/browse/OCPBUGS-62247
/cc @openshift/storage
see also: https://github.com/openshift/cluster-storage-operator/pull/621
=> OCPBUGS-62247: add all-egress label to deployments on HCP and IBM
